### ISSUE TITLE
Bearer Token API Example

### ISSUE THREAD

**Issue by sergey-msu** [azist/tutorial-steps#1]
Hey,
great framework!
I currently develop a web service and I looking for API that will allow external users of my service to authenticate through simple bearer token. I need to register users and assign them bearer token. 
Can I do so with azist? Is there any examples or tutorials?

**Comment by zhabis** [comment]
You can use OAuth authentication module to delegate user login and generate access tokens. I am planning to add tutorial steps for that. You would also need to interface with your IDP (Identity provider) system or use minidp system that Azos provides. How many users do you have?

**Comment by sergey-msu** [comment]
It would be great to see tutorial. thanks! We plan to have up to several thousands users till the end of the year, then may be more. 
It is normal to azist?

**Comment by itadapter** [comment]
In a week or so.

**Comment by sergey-msu** [comment]
👍
